Add Ledger Works to production-ready mirror node and explorer lists
hiero-ledger/hiero-docs pull request #124
Opened 2022-08-04 13:47 UTC by lw-chadschwab

Signed-off-by: Chad Schwab <chad.schwab@lworks.io>

**Description**:

This PR modifies updates mirror node documentation in order to support 
* Add Ledger Works to lists of production-ready mirror nodes and explorers

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ x] Documented (Code comments, README, etc.)
- [ n/a] Tested (unit, integration, etc.)

2022-08-04 14:25 UTC, lw-karlynelson submitted a review, later dismissed

2022-08-04 14:57 UTC, steven-sheehy requested changes
I think we should keep the list of explorers listed alphabetically everywhere since any other order could be seen as Hedera picking favorites.

2022-08-04 18:17 UTC, lw-chadschwab commented
@steven-sheehy done

2022-08-06 23:54 UTC, SimiHunjan approved these changes
Thank you so much for your contribution to the Hedera docs site! Looks great!

2022-08-06 23:54 UTC, merged