Fixed Auto Renew Documentation
hiero-ledger/hiero-docs pull request #273
Opened 2023-02-14 18:41 UTC by brianjohnson5972

**Description**:
Updated the auto renew documentation based on the recent rent changes.

**Related issue(s)**:
N/A

**Notes for reviewer**:
N/A

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-02-15 15:46 UTC, brianjohnson5972 commented
@theekrystallee I have been discussing with Greg Scullard about the current state of the Auto Renew methods on entities and he suggested to tag you for input. I believe all of these changes are correct and improvements on the current documentation, but wondering if you could suggest good improvements on further documenting the exact state that rent and Auto Renew is in for all these different entities.

2023-02-15 16:42 UTC, gregscullard requested changes
Made a few comments, see below, recommend fixing before merging

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/deprecated/sdks/consensus/create-a-topic.md
> +| `setAutoRenewPeriod(<autoRenewAccountId>)` | Duration  | Optional     |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/deprecated/sdks/cryptocurrency/create-an-account.md
> +| **Auto Renew Period**                | <p>The period of time in which the account will auto-renew in seconds. The account is charged tinybars for every auto-renew period. Duration type is in second
I think we should replace "DISABLED" with some description along the lines of the fact that rent is not enabled on accounts for now and may be in the future.
The AUTORENEW_DURATION_NOT_IN_RANGE error is still applicable (for smart contracts it can be between 1 and 3 months), not 100% sure about accounts, we should check if it's still locked to approx 3 months.

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/deprecated/sdks/cryptocurrency/create-an-account.md
> +| **Auto Renew Period**                | <p>The period of time in which the account will auto-renew in seconds. The account is charged tinybars for every auto-renew period. Duration type is in second
Or whether it follows the changes made for smart contract (1-3 months)

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/deprecated/sdks/cryptocurrency/update-an-account.md
> +| **Auto Renew Period**                | <p>The new period of time in which the account will auto-renew in seconds. The account is charged tinybars for every auto-renew period. Duration type is in se
Same comment as above

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/consensus-service/create-a-topic.md
> +| **Auto Renew Period**  | The initial lifetime of the topic and the amount of time to attempt to extend the topic's lifetime by automatically at the topic's expirationTime.
Same comment, topics aren't subject to rent for now, may be in the future.

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/consensus-service/create-a-topic.md
> +| `setAutoRenewPeriod(<autoRenewPeriod>)`    | Duration  | Optional     |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/consensus-service/update-a-topic.md
> +| **Auto Renew Period**  | Set a new auto-renew period for this topic.                                                         |
We should indicate rent may be coming in the future, in fact for topics it would make sense to plan on setting the auto renew account to a single "rent" account when creating lots of topics, this would alleviate the need to fund multiple accounts (although by default, the auto renew account is the transaction payer).

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/consensus-service/update-a-topic.md
> +| `setAutoRenewPeriod(<autoRenewPeriod>)`    | Duration  | Optional     |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/consensus-service/update-a-topic.md
> +| `getAutoRenewAccountId()` | AccountId | Optional     |
likely not optional, the value returned will be the accountId set during creation/update (defaults to tx paying account on create)

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/consensus-service/update-a-topic.md
> +| `getAutoRenewPeriod()`    | Duration  | Optional     |
not optional, there will be a value there

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/consensus-service/create-a-topic.md
> +| `getAutoRenewAccountId(<accountId>)`       | AccountId | Optional     |
it's not optional, a value will be returned (the account id specified during create/update or the tx payer at create if not otherwise specified)

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/consensus-service/create-a-topic.md
> +| `getAutoRenewPeriod(<autoRenewPeriod>)`    | Duration  | Optional     |
not optional, there will be a value there

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/cryptocurrency/create-an-account.md
> +| **Auto Renew Period**                | <p>The period of time in which the account will auto-renew in seconds. The account is charged tinybars for every auto-renew period. Duration type is in second
See comments above wrt AUTORENEW_DURATION_NOT_IN_RANGE error and note that while rent is disabled on accounts, it may be enabled in the future.

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/cryptocurrency/create-an-account.md
> +| `setAutoRenewPeriod(<autoRenewPeriod>)`           | Duration  | Optional    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/cryptocurrency/update-an-account.md
> +| **Auto Renew Period**                | <p>The new period of time in which the account will auto-renew in seconds. The account is charged tinybars for every auto-renew period. Duration time is in se
Same as above

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/cryptocurrency/update-an-account.md
> +| `setAutoRenewPeriod(<duration>)`                  | Duration  | Optional    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/create-a-smart-contract.md
> +Smart contract entity auto renewal and expiry has been enabled. Please check out [HIP-16](https://hips.hedera.com/hip/hip-16) for more information.
Also reference https://hips.hedera.com/hip/hip-372

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/create-a-smart-contract.md
> +| **Auto Renew Account ID**        | An account to charge for auto-renewal of this contract. If not set, or set to an account with zero hbar balance, the contract's own hbar balance will be used to c
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/create-a-smart-contract.md
> +| **Auto Renew Period**            | The period that the instance will charge its account every this many seconds to renew.
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/create-a-smart-contract.md
> +| `setAutoRenewAccountId(<accountId)`                 | AccountId                                | Optional    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/create-a-smart-contract.md
> +| `setAutoRenewPeriod(<autoRenewPeriod>)`             | Duration                                 | Optional    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/create-a-smart-contract.md
> +| `getAutoRenewAccountId()`                           | AccountId  | Optional    |
Not optional

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/create-a-smart-contract.md
> +| `getAutoRenewPeriod()`                              | Duration   | Optional    |
Not optional

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/update-a-smart-contract.md
> +| `clearAutoRenewAccountId()`                       |                                                  | Optional    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/update-a-smart-contract.md
> +| `getAutoRenewAccountId()`   | AccountId                                        | Optional    |
Not optional

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/smart-contracts/update-a-smart-contract.md
>  | `getAutoRenewPeriod()`      | Duration                                         | Optional    |
Not optional

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/tokens/define-a-token.md
> +| **Auto Renew Period**  | The interval at which the auto-renew account will be charged to extend the token's expiry. The default auto-renew period is 7,890,000 seconds.
We should mention that while rent is not enabled on tokens, it may be in the future.

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/tokens/define-a-token.md
> +| `setTreasuryAccountId(<treasury>)`    | [AccountId](../specialized-types.md#accountid)                    | Required    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/tokens/define-a-token.md
> -| `setExpirationTime(<expirationTime>)` | Instant                                                           | Optional    |
setExpirationTime is a method in the JS sdk for creating tokens

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/tokens/define-a-token.md
> +| `setAutoRenewAccountId(<account>)`    | [AccountId](../specialized-types.md#accountid)                    | Optional    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/tokens/define-a-token.md
> +| `setAutoRenewPeriod(<period>)`        | Duration                                                          | Optional    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/tokens/update-a-token.md
> +| **Auto Renew Period**  | The new interval at which the auto-renew account will be charged to extend the token's expiry. The default auto-renew period is 7,890,000 seconds.
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/tokens/update-a-token.md
> +| `setAutoRenewAccountId(<account>)`    | [AccountId](../specialized-types.md#accountid) | Optional    |
LGTM

2023-02-15 16:42 UTC, gregscullard commented on sdks-and-apis/sdks/tokens/update-a-token.md
> +| `setAutoRenewPeriod(<period>)`        | Duration                                       | Optional    |
LGTM

2023-02-15 18:01 UTC, brianjohnson5972 commented on sdks-and-apis/sdks/consensus-service/update-a-topic.md
> +| `getAutoRenewAccountId()` | AccountId | Optional     |
Yeah, wasn't paying attention, just copied Optional on through. So everything getTopicId() and getAdminKey() should be Required as well, right? (And getSubmitKey() and getTopicMemo() stay Optional)

2023-02-15 19:08 UTC, brianjohnson5972 commented on sdks-and-apis/deprecated/sdks/cryptocurrency/create-an-account.md
> +| **Auto Renew Period**                | <p>The period of time in which the account will auto-renew in seconds. The account is charged tinybars for every auto-renew period. Duration type is in second
Ok, my brain was reading "fixed to" as "set as" and was assuming this was no longer applicable.  I will change the smart contracts one to indicate the min and max seconds values. The services code (https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/validation/ContextOptionValidator.java#L153) looks like the min and max limits are in place, unless the config file has min and max set to the same value, or other code paths that may be restricting it. I will put the 1 month to 3 month range comment in and you guys can figure out if that is correct. Also, will add a comment indicating that rent is not currently active.

2023-02-15 19:37 UTC, brianjohnson5972 commented on sdks-and-apis/deprecated/sdks/cryptocurrency/create-an-account.md
> +| **Auto Renew Period**                | <p>The period of time in which the account will auto-renew in seconds. The account is charged tinybars for every auto-renew period. Duration type is in second
Since the max value is set based on the configuration parameter, and the configuration file in the repo has 8000001(https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties#L116), which is effectively 92 days (this is what was quoted in the smart contract rent zoom session as the upper end) should I use that value?

2023-02-15 20:33 UTC, brianjohnson5972 commented on sdks-and-apis/sdks/consensus-service/update-a-topic.md
> +| **Auto Renew Period**  | Set a new auto-renew period for this topic.                                                         |
Are you indicating to add this information to the comments?

2023-02-15 21:47 UTC, brianjohnson5972 commented on sdks-and-apis/sdks/tokens/define-a-token.md
> -| `setExpirationTime(<expirationTime>)` | Instant                                                           | Optional    |
I must have accidentally deleted this.

2023-03-02 14:47 UTC, gregscullard commented on sdks-and-apis/deprecated/sdks/cryptocurrency/create-an-account.md
> +| **Auto Renew Period**                | <p>The period of time in which the account will auto-renew in seconds. The account is charged tinybars for every auto-renew period. Duration type is in second
LGTM

2023-03-02 14:48 UTC, gregscullard approved these changes, later dismissed
Changes made since last review look good - thank you for taking the time.

2023-03-02 17:17 UTC, theekrystallee approved these changes
Looks great! Thank you for the PR @brianjohnson5972 !

2023-03-02 17:17 UTC, merged