Update instructions to build and run the rpc relay
hiero-ledger/hiero-docs pull request #371
Opened 2023-06-21 16:16 UTC by satwikkansal

Docs were missing couple of steps to build and run the relay server

2023-06-24 00:53 UTC, bguiz commented on tutorials/more-tutorials/json-rpc-connections/hedera-json-rpc-relay.md
> +* (11) Run `npm run build`. This will clean and compile the relay library and the server.
```suggestion
* (10) Run `npm run setup` to link dependencies within its sub-packages.
* (11) Run `npm run build` to build the full project.
```

2023-06-24 13:58 UTC, satwikkansal commented
@bguiz I have committed your suggestions :)

2023-06-24 23:25 UTC, theekrystallee requested changes
Hi @satwikkansal, thanks for the PR! One last thing before we merge, could you please include a `Signed-off-by` line in the commit message? [Here](https://github.com/hashgraph/hedera-docs/pull/371/checks) are steps to resolve the failed check.

Once the DCO check passes, will approve and merge. Thanks again!

2023-06-26 11:30 UTC, satwikkansal commented
@theekrystallee done now!

2023-06-26 19:18 UTC, theekrystallee approved these changes

2023-06-26 19:19 UTC, merged