docs: Hello World seq: 00 create fund account #2
hiero-ledger/hiero-docs pull request #481
Opened 2023-11-03 07:23 UTC by bguiz

**Description**:

## What

- Add a new hello world sequence
- Create and fund an account

## Why

- Pre-requisite for the other hello world sequences

**Related issue(s)**:

- Preview PR: https://github.com/hedera-dev/preview-hedera-docs/pull/2

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)
  - `npm run test`

2023-11-03 14:19 UTC, theekrystallee requested changes
@bguiz Please use [this](https://github.com/hashgraph/hedera-docs/blob/master/tutorials/smart-contracts/deploy-a-smart-contract-using-hardhat-hedera-json-rpc-relay.md) tutorial as a reference to modify the style/format for this "Hello World" tutorial series and resubmit.

2023-11-03 14:19 UTC, theekrystallee commented on SUMMARY.md
> +* [Hello World](hello-world/README.md)
are you suggesting we create a new section dedicated to these "Hello World" tutorials? this location for a tutorial series is out of place

2023-11-03 14:19 UTC, theekrystallee commented on hello-world/create-fund-account.md
> +## Create and fund an account
Tutorial title should be H1 header

2023-11-03 14:19 UTC, theekrystallee commented on hello-world/create-fund-account.md
> +
Please add dividers (`---`) between each H2 header sections

2023-11-03 14:19 UTC, theekrystallee commented on hello-world/create-fund-account.md
> +## Before you begin
Consider renaming to `Prerequisites`

2023-11-03 14:19 UTC, theekrystallee commented on hello-world/create-fund-account.md
> +
Add Table of Contents.

[Reference](https://github.com/hashgraph/hedera-docs/blob/master/tutorials/smart-contracts/deploy-a-smart-contract-using-hardhat-hedera-json-rpc-relay.md#table-of-contents-)

2023-11-03 14:19 UTC, theekrystallee commented on hello-world/create-fund-account.md
Please use [this](https://github.com/hashgraph/hedera-docs/blob/master/tutorials/smart-contracts/deploy-a-smart-contract-using-hardhat-hedera-json-rpc-relay.md) tutorial as a reference to modify the style/format/ for this "Hello World" tutorial series. Below is also how we've been structuring/ordering tutorial content. 

Content organized in this order:
1. Intro (what you will accomplish can go in this section)
2. Prerequisites (before you begin)
3. Table of Contents
4. Tutorial Steps (Set up project, Create account, Write, Run script)
5. Next Steps (cheat sheet?)
6. List of Additional Resources (project repo, other docs/repo)
7. Writer/Editor Credits

Style/format notes:
- Dividers between each H2 header
-- Set up project, Create account, Write, Run script should be H2 headers
- The tutorial title should be H1

2023-11-04 01:05 UTC, theekrystallee commented on hello-world/create-fund-account.md
> +```
I suggest just linking [this](https://docs.hedera.com/hedera/getting-started/introduction) page for this step and moving it into the **Prerequisite/Before you begin**

Or

Putting the steps inside a dropdown/expandable and moving it up to Prerequisites

<details>

<summary>Create account</summary>

Visit the Hedera Portal, and create a Testnet account.

[![localhost-init-step-03][5]][5]

Copy-paste the confirmation code sent to your email.

[![localhost-init-step-04][6]][6]

Fill out this form.

[![localhost-init-step-05][7]][7]

In the top-left select Hedera Testnet from the drop-down.

[![localhost-init-step-06a][8]][8]

From the next screen that shows your accounts,
copy the value of "DER encoded private key",
and replace `YOUR_OPERATOR_KEY` in the `.env` file with it.

[![ocalhost-init-step-06b-07][9]][9]

From the same screen, copy the value of "Account ID", and replace `YOUR_OPERATOR_ID` in the `.env` file with it.

For example, if your Account ID is `0.0.123`,
and your DER encoded private key is `302e0201234`,
the 2 lines in your `.env` file should look like this:

```text
ACCOUNT_ID=0.0.123
ACCOUNT_PRIVATE_KEY=302e0201234
```
</details>

2023-11-04 11:24 UTC, bguiz reviewed
New preview link for review: https://hedera-dev.gitbook.io/preview-hedera-docs/~/revisions/eQyFlejAwChYOdyqR5Z1/tutorials/hello-world/create-fund-account

2023-11-04 11:24 UTC, bguiz commented on SUMMARY.md
> +* [Hello World](hello-world/README.md)
I'll update to put under `/tutorials` - does that work for you?

2023-11-04 11:24 UTC, bguiz commented on hello-world/create-fund-account.md
> +## Create and fund an account
OK!

2023-11-04 11:24 UTC, bguiz commented on hello-world/create-fund-account.md
> +
OK!

2023-11-04 11:24 UTC, bguiz commented on hello-world/create-fund-account.md
> +## Before you begin
OK!

2023-11-04 11:24 UTC, bguiz commented on hello-world/create-fund-account.md
> +
🤔 Hmm, that link - https://github.com/hashgraph/hedera-docs/blob/master/tutorials/smart-contracts/deploy-a-smart-contract-using-hardhat-hedera-json-rpc-relay.md#table-of-contents -  404s

2023-11-04 11:24 UTC, bguiz commented on hello-world/create-fund-account.md
> +
Also, docbook auto-generates a table of contents for you (see top right in screen shot) - isn't this sufficient?
![image](https://github.com/hashgraph/hedera-docs/assets/1773785/ae178d95-82fb-4e5e-8b40-5f8c62765973)

2023-11-04 11:24 UTC, bguiz commented on hello-world/create-fund-account.md
> +```
The linked page - https://docs.hedera.com/hedera/getting-started/introduction - is insufficient, as it does not contain all the steps outlined here. Not to mention the use of a `.env` file being integrated. So that's not going to work.
I'll go for the expandable instead, within the create account section though (not prerequisites).

2023-11-04 11:24 UTC, bguiz commented on hello-world/create-fund-account.md
Alright, addressed all comments,
except for table of comments [see here](https://github.com/hashgraph/hedera-docs/pull/481/files#r1381749768).

2023-11-04 11:24 UTC, bguiz commented on hello-world/create-fund-account.md
New preview link for review: https://hedera-dev.gitbook.io/preview-hedera-docs/~/revisions/eQyFlejAwChYOdyqR5Z1/tutorials/hello-world/create-fund-account

2023-11-08 13:23 UTC, bguiz commented
@theekrystallee New preview link for review: https://hedera-dev.gitbook.io/preview-hedera-docs/~/revisions/SzOayLupZ5F3CuprpzGE/tutorials/hello-world/create-fund-account

2023-11-08 16:21 UTC, theekrystallee approved these changes
Thanks for making the changes @bguiz. Looks good.

2023-11-08 16:22 UTC, merged