Add setup-foundry-and-write-basic-unit-test tutorial
hiero-ledger/hiero-docs pull request #541
Opened 2024-01-18 18:39 UTC by a-ridley

**Description**:

This tutorial is the first in a short mini-series of testing hedera smart contracts using foundry testing features. The goal is for this first one in the series to replace the standalone tutorial located [here](https://docs.hedera.com/hedera/tutorials/smart-contracts/how-to-set-up-foundry-to-test-smart-contracts-on-hedera). This new tutorial is essentially a revamp of the tutorial linked.

Introducing a new section dedicated to Foundry under Smart Contracts, designed to house all tutorials related to Foundry. 

* a README.md file which introduces Foundry
* A markdown file that outlines the steps to the first tutorial

**Notes for reviewer**:
* The goal is for this first one in the series to replace the standalone tutorial located [here](https://docs.hedera.com/hedera/tutorials/smart-contracts/how-to-set-up-foundry-to-test-smart-contracts-on-hedera). Therefore, once this is approved, we will need to take down the old one.

2024-01-20 03:54 UTC, theekrystallee requested changes
Please review the errors I encountered and modify the code if necessary and resubmit. Other than those errors, looks great!

2024-01-20 03:54 UTC, theekrystallee commented on tutorials/smart-contracts/foundry/setup-foundry-and-write-basic-unit-test.md
> +forge build
I ran into a few errors when trying to `forge build`

**First error:**

```bash
Compiler run failed:
Error (7920): Identifier not found or not unique.
 --> test/TodoList.t.sol:7:26:
  |
7 | contract TodoListTest is Test {
  |               
```

**Solution**: I had to update the import path on line 4 of `ToDoList.t.sol` to:
```sol
import "lib/forge-std/src/Test.sol";
```
The import path in `Test.sol` needed to be updated to:
```sol
import {DSTest} from "lib/forge-std/lib/ds-test/src/test.sol";
```

**Second error**: 
```bash
Compiler run failed:
Error (6160): Wrong argument count for function call: 2 arguments given but expected 1.
  --> test/TodoList.t.sol:23:38:
   |
23 |         uint256 numberOfTodosAfter = todoList.createTodo(
   |                                      ^ (Relevant source part starts here and spans across multiple lines).
```

**Solution**: remove one of the arguments in the `test_createTodo_returnsNumberOfTodosIncrementedByOne` function in `ToDoList.t.sol` 

I just commented out line 24 where `address(this)` on line 24 but not sure if the function was meant to take an address AND a string. The `createTodo` function in `ToDoList.sol` needs to be adjusted if that is the case.
<img width="553" alt="Screenshot 2024-01-19 at 7 39 15 PM" src="https://github.com/hashgraph/hedera-docs/assets/56278409/32ac3d6d-23b5-4b45-8769-bd72c9bc6f1b">

`forge build` ran successfully after I made the above edits to the code.
<img width="490" alt="Screenshot 2024-01-19 at 7 47 01 PM" src="https://github.com/hashgraph/hedera-docs/assets/56278409/3d924fa4-da2c-41c7-a24c-58f766f234be">

2024-01-22 21:16 UTC, a-ridley commented on tutorials/smart-contracts/foundry/setup-foundry-and-write-basic-unit-test.md
> +forge build
Great catch Krystal! 

Line 24 has an unnecessary argument. It is needed for the next tutorial but not this first one. I'll update the code.

As for the import issues, I will need to clarify the steps a bit more because the remappings.txt file should take care of it, and there shouldn't be any changes to the import. I'll run through the setup up part on a brand new laptop to double check.

2024-01-22 22:26 UTC, a-ridley commented
I added steps to ensure `foundryup` is installed in order to be able to use the `forge` command. I also removed the unnecessary argument that was in the test and causing issues. In addition, I moved the step to open the project in a code editor before creating the remappings.txt file. I re-ran through the tutorial on a laptop that did not have foundry previously set up & was able to run `forge build` without any issues.  Let me know if you still run into the import errors. The remappings file should make it so no changes to the import line should be needed. :)

2024-01-22 23:02 UTC, theekrystallee approved these changes

2024-01-22 23:03 UTC, merged