Docs: Add Tutorial on How to Setup Hedera Local Node using NPM CLI
hiero-ledger/hiero-docs pull request #715
Opened 2024-06-27 10:54 UTC by owans

**Description**:

* Added Tutorial on How to Setup Hedera Local Node using NPM CLI

**Related issue(s)**:
* NIL

**Notes for reviewer**:
* NIL

**Checklist**
- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-06-27 20:37 UTC, theekrystallee requested changes
Thanks so much for the PR! This looks great. Just resolve a few of my comments and it should be ready to merge.

2024-06-27 20:37 UTC, theekrystallee commented on tutorials/local-node/setup-hedera-node-cli-npm.md
> +Hedera is an open-source, public, proof-of-stake network. Its network services offer low & fixed fees,10k TPS, and instant transaction finality. Learn more about the [Hedera platform and how it works
1. we like to spell out the "&" typically. suggest: "low and fixed"
2. add a space between the first "," and "10k"

2024-06-27 20:37 UTC, theekrystallee commented on tutorials/local-node/setup-hedera-node-cli-npm.md
> +* [Node.js](http://Node.js) >= v14.x (Check version: node -v)
1. replace the nodejs link http://node.js link to https://nodejs.org/
2. we like to highlight all commands that will be run in the terminal. please include the "``" backtick around the `node -v` command

2024-06-27 20:37 UTC, theekrystallee commented on tutorials/local-node/setup-hedera-node-cli-npm.md
> +* [Docker Compose](https://docs.docker.com/compose/) >= v2.12.2 (Check version: docker compose version)
same comment as the last of to include "``" around the terminal commands

`npm -v`
`docker -v`
`docker compose version`

2024-06-27 20:37 UTC, theekrystallee commented on tutorials/local-node/setup-hedera-node-cli-npm.md
> +Clone the Github repo, navigate to the project folder using the commands below;
GitHub has a capital H

2024-06-28 09:27 UTC, owans commented on tutorials/local-node/setup-hedera-node-cli-npm.md
> +Hedera is an open-source, public, proof-of-stake network. Its network services offer low & fixed fees,10k TPS, and instant transaction finality. Learn more about the [Hedera platform and how it works
Noted. Thank you

2024-06-28 09:27 UTC, owans commented on tutorials/local-node/setup-hedera-node-cli-npm.md
> +* [Docker Compose](https://docs.docker.com/compose/) >= v2.12.2 (Check version: docker compose version)
Thank you

2024-06-28 09:27 UTC, owans commented on tutorials/local-node/setup-hedera-node-cli-npm.md
> +Clone the Github repo, navigate to the project folder using the commands below;
Good spot, will resolve

2024-06-28 10:16 UTC, owans commented
Fixes resolved. Thank you for the feedback @theekrystallee.

2024-07-02 20:19 UTC, theekrystallee approved these changes
Thanks so much for making the changes that we asked for and for the additional points of clarity. This looks great!

2024-07-02 20:19 UTC, merged